repos:
  - repo: local
    hooks:
      - id: autoflake
        name: Remove unused imports and variables
        entry: autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place --exclude=__init__.py ./src
        language: system
        pass_filenames: false
        always_run: true

      - id: isort
        name: Sort imports
        entry: isort ./src --profile black
        language: system
        pass_filenames: false
        always_run: true

      - id: bandit
        name: Security check
        entry: bandit -r ./src -s B311,B608,B301,B403
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff
        name: Run the linter.
        entry: ruff ./src --fix
        language: system
        pass_filenames: false
        types: [ python ]

      - id: ruff-format
        name: Run the formatter.
        entry: ruff format ./src
        language: system
        pass_filenames: false
        types: [ python ]

#      - id: tests
#        name: Run tests
#        entry: pytest -v
#        always_run: true
#        pass_filenames: false
#        language: system