FROM python:3.10-slim

ARG SPACY_MODEL_CORE

RUN apt-get update && \
    rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8

WORKDIR /app

COPY requirements /requirements

RUN pip install --no-cache-dir -r /requirements/base.txt

RUN python3 -m spacy download $SPACY_MODEL_CORE