FROM python:3.10-slim-buster

RUN apt-get update && \
    rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8

WORKDIR /app

COPY requirements /requirements

RUN pip install --no-cache-dir -r /requirements/base.txt